
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-agent
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: metrics-agent
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
