name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make

      - name: Build C++ metrics agent
        run: |
          g++ src/main.cpp -o metrics-agent -Iinclude -pthread

      - name: Build Docker image
        run: docker build -t metrics-agent:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: georgikrumov16-cyber
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image
        run: docker tag metrics-agent:latest ghcr.io/georgikrumov16-cyber/metrics-agent:latest

      - name: Push image
        run: docker push ghcr.io/georgikrumov16-cyber/metrics-agent:latest



